In [17]:
import requests
from bs4 import BeautifulSoup

In [18]:
#URL for scraping data

url = 'https://www.worldometers.info/coronavirus/countries-where-coronavirus-has-spread/'

In [19]:
#get URL html

page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser')

data = []

In [20]:
#Scraping every element in the url's table

data_iterator = iter(soup.find_all('td'))

In [21]:
#Loop will keep repeating until there is data available in the iterator

while True:
    try:
        country = next(data_iterator).text
        confirmed = next(data_iterator).text
        deaths = next(data_iterator).text
        continent = next(data_iterator).text
 
        data.append((
            country,
            int(confirmed.replace(',', '', 26723249)),
            int(deaths.replace(',', '', 196487)),
            continent
        ))
 
    except StopIteration:
        break

In [22]:
#Sorting the data by the number of confirmed cases

data.sort(key = lambda row: row[1], reverse = True)

In [23]:
import texttable as tt
table = tt.Texttable()

In [24]:
table.add_rows([(None, None, None, None)] + data)

table.set_cols_align(('c', 'c', 'c', 'c'))
table.header((' Country ', ' Number of Cases ', ' Deaths ', ' Continent '))

In [25]:
print(table.draw())

+---------------------------+-------------------+----------+-------------------+
|          Country          |  Number of Cases  |  Deaths  |     Continent     |
+===========================+===================+==========+===================+
|       United States       |     1.118e+08     | 1219487  |   North America   |
+---------------------------+-------------------+----------+-------------------+
|           India           |     45035393      |  533570  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          France           |     40138560      |  167642  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Germany          |     38828995      |  183027  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Brazil           |     38743918      |  711380  |   South America   |
+---------------------------+-------------------+----------+-------------------+
|        South Korea        |     34571873      |  35934   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
| Japan (+Diamond Princess) |     33804284      |  74707   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|           Italy           |     26723249      |  196487  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|      United Kingdom       |     24910387      |  232112  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Russia           |     24124215      |  402756  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Turkey           |     17232066      |  102174  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|           Spain           |     13914811      |  121760  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Australia         |     11853144      |  24414   | Australia/Oceania |
+---------------------------+-------------------+----------+-------------------+
|          Vietnam          |     11625195      |  43206   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Taiwan           |     10241523      |  19005   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Argentina         |     10128845      |  130841  |   South America   |
+---------------------------+-------------------+----------+-------------------+
|        Netherlands        |      8635786      |  22992   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Mexico           |      7702809      |  334958  |   North America   |
+---------------------------+-------------------+----------+-------------------+
|           Iran            |      7627186      |  146811  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Indonesia         |      6829221      |  162063  |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Poland           |      6661991      |  120598  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Colombia          |      6400173      |  143200  |   South America   |
+---------------------------+-------------------+----------+-------------------+
|          Greece           |      6101379      |  37869   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Austria          |      6081287      |  22542   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Portugal          |      5643062      |  28126   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Ukraine          |      5557995      |  112418  |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|           Chile           |      5384853      |  64497   |   South America   |
+---------------------------+-------------------+----------+-------------------+
|         Malaysia          |      5278406      |  37348   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Canada           |      4946090      |  59034   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Belgium          |      4861695      |  34376   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Israel           |      4841772      |  12707   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|        North Korea        |      4772813      |    74    |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Thailand          |      4770149      |  34586   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
| Czech Republic (Czechia)  |      4759041      |  43517   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|           Peru            |      4572667      |  222161  |   South America   |
+---------------------------+-------------------+----------+-------------------+
|        Switzerland        |      4453053      |  14452   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|        Philippines        |      4140383      |  66864   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|       South Africa        |      4076463      |  102595  |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Romania          |      3529735      |  68929   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Denmark          |      3183756      |   8814   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Singapore         |      3006155      |   2024   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Hong Kong         |      2937609      |  14924   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Sweden           |      2754129      |  27407   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|        New Zealand        |      2621111      |   5697   | Australia/Oceania |
+---------------------------+-------------------+----------+-------------------+
|          Serbia           |      2615054      |  18057   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|           Iraq            |      2465545      |  25375   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Hungary          |      2230232      |  49048   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|        Bangladesh         |      2049377      |  29493   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Slovakia          |      1877605      |  21224   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Georgia          |      1861665      |  17132   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Jordan           |      1746997      |  14122   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Ireland          |      1734582      |   9491   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Pakistan          |      1581936      |  30664   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Finland          |      1516117      |  11958   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Norway           |      1509732      |   6638   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|        Kazakhstan         |      1411831      |  13848   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Lithuania         |      1397806      |   9897   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Slovenia          |      1356546      |   7100   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Bulgaria          |      1339851      |  38748   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Croatia          |      1309728      |  18687   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Guatemala         |      1291293      |  20289   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Morocco          |      1278992      |  16303   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Lebanon          |      1243838      |  10952   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|        Costa Rica         |      1238883      |   9428   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Bolivia          |      1212131      |  22407   |   South America   |
+---------------------------+-------------------+----------+-------------------+
|          Tunisia          |      1153361      |  29423   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|           Cuba            |      1115251      |   8530   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Ecuador          |      1070188      |  36043   |   South America   |
+---------------------------+-------------------+----------+-------------------+
|   United Arab Emirates    |      1067030      |   2349   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Panama           |      1059893      |   8727   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Uruguay          |      1041111      |   7664   |   South America   |
+---------------------------+-------------------+----------+-------------------+
|         Mongolia          |      1011496      |   2284   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|           Nepal           |      1003450      |  12031   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Belarus          |      994037       |   7118   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Latvia           |      982505       |   6715   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|       Saudi Arabia        |      841469       |   9646   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Paraguay          |      837602       |  20155   |   South America   |
+---------------------------+-------------------+----------+-------------------+
|        Azerbaijan         |      835234       |  10400   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Bahrain          |      729549       |   1574   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Cyprus           |      681110       |   1365   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|    Dominican Republic     |      675890       |   4384   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|         Sri Lanka         |      672754       |  16897   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Kuwait           |      667158       |   2570   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Myanmar          |      641873       |  19495   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Moldova          |      635145       |  12218   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Estonia          |      628070       |   3001   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|    State of Palestine     |      621008       |   5404   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Venezuela         |      552695       |   5856   |   South America   |
+---------------------------+-------------------+----------+-------------------+
|           Egypt           |      516023       |  24613   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|           Qatar           |      514524       |   690    |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|           Libya           |      507274       |   6437   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|           China           |      503302       |   5272   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|         Ethiopia          |      501157       |   7574   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Réunion          |      494595       |   921    |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|         Honduras          |      474590       |  11165   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|          Armenia          |      451831       |   8777   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|  Bosnia and Herzegovina   |      403615       |  16388   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|           Oman            |      399449       |   4628   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|        Luxembourg         |      391232       |   1232   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|      North Macedonia      |      350567       |   9976   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Zambia           |      349304       |   4069   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|           Kenya           |      344130       |   5689   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Brunei           |      343719       |   225    |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Albania          |      334863       |   3605   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|         Botswana          |      330638       |   2801   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|        Montenegro         |      296542       |   2846   |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|          Algeria          |      272010       |   6881   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Nigeria          |      267188       |   3155   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|         Zimbabwe          |      266359       |   5740   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|        Uzbekistan         |      253662       |   1637   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|        Afghanistan        |      234174       |   7996   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|        Mozambique         |      233731       |   2250   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|        Martinique         |      230354       |   1102   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|           Laos            |      218970       |   758    |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Iceland          |      209906       |   229    |      Europe       |
+---------------------------+-------------------+----------+-------------------+
|        Kyrgyzstan         |      206897       |   2991   |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|        Guadeloupe         |      203235       |   1021   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|        El Salvador        |      201855       |   4230   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|    Trinidad and Tobago    |      191496       |   4390   |   North America   |
+---------------------------+-------------------+----------+-------------------+
|         Maldives          |      186694       |   316    |       Asia        |
+---------------------------+-------------------+----------+-------------------+
|          Namibia          |      172389       |   4106   |      Africa       |
+---------------------------+-------------------+----------+-------------------+
|          Uganda           |      172149       |   3632   |      Africa       |